### PR TITLE
Add support for completion block on `present` method

### PR DESCRIPTION
**Pull request by Sumolari**
## Pull request checklist

- [X] All tests pass. Demo project builds and runs.
- [X] I have resolved any merge conflicts.
- [X] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines), and reviewed the [contributing guidelines](https://github.com/jessesquires/HowToContribute).

## What's in this pull request?

Adds `completion` parameter to `present` method to allow setting a completion block that will be called when presented view controller is completely presented (after presentation animation finishes).

Completion block is ignored when presentation type is `show` or `showDetail`.

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks @Sumolari ! 😄 

The completion blocks here were intentionally left out. There was a similar PR at #7. 

See my comment there, https://github.com/jessesquires/PresenterKit/pull/7#issuecomment-204489336.

I'm not sure about this change... 🤔 What's your use case?

**Comment by psartzetakis** [comment]
Hi All, 😄

@jessesquires , I was thinking of the following scenario (that fits better in the modal presentation).
There has been the case that `viewControllerA` presents (`modally`) `viewControllerB`. However when `viewControllerB` has been completely dismissed I might want to run an animation in `viewControllerA` and I would like the user to experience the whole animation. `viewWillAppear` or `viewDidAppear` might not be the best place to do such a thing  (although there are workarounds). If I want to pass any data from `viewControllerB` to `viewControllerA` I could do it through closure or delegation (or whatever) but If I want to signal to `viewControllerA` that  `viewControllerB` has been completely dismissed doing it through the completion handler might be a good idea. 🤔.
What do you think?

**Comment by jessesquires** [comment]
@psartzetakis -- True, and I've seen this done before... but 🤷‍♂️ I'm still not completely convinced.

In this situation I'd argue that custom VC animations are probably a better solution. Not sure.

Even if you are using this library, you could always fallback to UIKit for these one-off special cases

**Comment by psartzetakis** [comment]
@jessesquires , I totally agree with you , it is a rare case and if need be they can always fallback to `UIKit`. I can understand your concern that completion handlers can be easily misused and that is something that you want to avoid through this library. However if the users want to misuse the completion handler they can fallback to the `UIKit` ..😅.  So probably the main question is if it is ok to use constantly `PresenterKit` at all times or swapping between `PresenterKit` and `UIKit`..😕
That's all from me, I hope my perspective was helpful in any way  😊. Thanks for your time discussing it. 👍🏻

**Comment by jessesquires** [comment]
Thanks @psartzetakis ! 🎉 😄 

All very good points. I'll think about this some more. 🤔

**Comment by jessesquires** [comment]
Hey all -- sorry for the delay here. I've decided to take this 😄 

Working on finishing up and releasing 4.0 today. 🎉

**Comment by jessesquires** [comment]
I'll merge manually and resolve conflicts. 😊

**Pull request merged**
