### PR TITLE
add a completion handler for `-dismiss()`

### PR DESCRIPTION
**Pull request by Limon-O-O**
add a completion handler for `-dismiss()`

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks @Limon-O-O ! :smile: 

A couple of things here:

Personally, I've **never** used this parameter and that's one reason why it was intentionally omitted. To me, doing almost anything in the `completion` block here is a code smell — usually the view lifecycle methods are more appropriate (and better) for any cleanup or teardown for a view controller.

Aside from that, now the behavior here is a bit weird given this is possibly using `popViewControllerAnimated`, where there is no `completion` parameter.

Let me know if there's a good use-case that I'm missing! :blush:

**Comment by Limon-O-O** [comment]
I have a tableView, like this 

simulator screen shot apr 3 2016 7 00 05 pm

And I want to call a protocol method `source?.didSelectRowAtIndex(indexPath.row)` in completion()

```
func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        tableView.deselectRowAtIndexPath(indexPath, animated: true)

        dismiss() {
            self.source?.didSelectRowAtIndex(indexPath.row)
        }
    }
```

**Comment by Limon-O-O** [comment]
Take your advice, 

```
override func viewDidDisappear(animated: Bool) {
   super.viewDidDisappear(animated)

    if let didSelectRow = didSelectedRow {
        source?.didSelectRowAtIndex(didSelectRow)
    }
 }
```

**Comment by jessesquires** [comment]
@Limon-O-O :+1: 

It looks like you are keeping a var to track this state, `didSelectRow` — but you don't need to:

1. don't call `deselectRowAtIndexPath` inside `didSelectRowAtIndexPath`
2. use `indexPathForSelectedRow` inside `viewDidDisappear`

```swift
override func viewDidDisappear(animated: Bool) {
   super.viewDidDisappear(animated)

    if let indexPath = tableView.indexPathForSelectedRow {
        tableView.deselectRowAtIndexPath(indexPath, animated: true)
        source?.didSelectRowAtIndex(indexPath)
    }
 }
```

**Comment by Limon-O-O** [comment]
Wow, help me a lot, thanks :)

**Pull request closed without merging**
